[package]
name = "pe-version"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
specta.workspace = true
dlssync-contracts = { path = "../dlssync-contracts" }
pelite.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[dev-dependencies]
tempfile.workspace = true
